# Okta App Configuration Schema - Enhanced Version
# This schema defines the structure and validation rules for app configurations
# New folder structure: apps/DIVISION/APPNAME/ENVIRONMENT/app-config.yaml

type: object
required:
  - parent_cmdb_name
  - division_name
  - cmdb_app_short_name
  - environment
  - team_dl
  - requested_by
  - app_config
  - oauth_config
properties:
  parent_cmdb_name:
    type: string
    description: "Human-readable application name (Parent CMDB Name)"
  
  division_name:
    type: string
    enum: ["DIV1", "DIV2", "DIV3", "DIV4", "DIV5", "DIV6"]
    description: "Division name (must match folder name)"
  
  cmdb_app_short_name:
    type: string
    pattern: '^[A-Z0-9]+$'
    description: "CMDB app short name (e.g., XYZ for XYZ Application)"
  
  environment:
    type: string
    enum: ["dev", "uat", "prod"]
    description: "Environment name (must match folder name)"
  
  team_dl:
    type: string
    format: email
    description: "Team distribution list email for this app"
  
  requested_by:
    type: string
    format: email
    description: "Email of person who requested this app"
  
  # App Configuration - what to create
  app_config:
    type: object
    required:
      - create_2leg
      - create_3leg_frontend
      - create_3leg_backend
      - create_3leg_native
      - create_saml
    properties:
      create_2leg:
        type: boolean
        description: "Create 2-leg OAuth app (client credentials)"
      
      create_3leg_frontend:
        type: boolean
        description: "Create 3-leg frontend OAuth app (SPA with PKCE)"
      
      create_3leg_backend:
        type: boolean
        description: "Create 3-leg backend OAuth app (web app with client secret)"
      
      create_3leg_native:
        type: boolean
        description: "Create 3-leg native OAuth app (password grant)"
      
      create_saml:
        type: boolean
        description: "Create SAML app (not implemented yet)"
        default: false
  
  # OAuth Configuration - OAuth app settings
  oauth_config:
    type: object
    properties:
      # OAuth App Settings
      scopes:
        type: array
        items:
          type: string
        description: "OAuth scopes to request"
        default: []
      
      redirect_uris:
        type: array
        items:
          type: string
          format: uri
        description: "Redirect URIs for the application"
        default: []
      
      post_logout_uris:
        type: array
        items:
          type: string
          format: uri
        description: "Post-logout redirect URIs for the application"
        default: []
  
  # Trusted Origins configuration
  trusted_origins:
    type: array
    description: "List of trusted origins for CORS and redirect"
    items:
      type: object
      required:
        - name
        - url
      properties:
        name:
          type: string
          description: "Trusted origin name"
        url:
          type: string
          format: uri
          description: "Trusted origin URL"
        scopes:
          type: array
          items:
            type: string
            enum: ["CORS", "REDIRECT"]
          description: "Trusted origin scopes"
          default: ["CORS"]
        status:
          type: string
          enum: ["ACTIVE", "INACTIVE"]
          description: "Trusted origin status"
          default: "ACTIVE"
  
  # Bookmarks configuration
  bookmarks:
    type: array
    description: "List of bookmark apps for admin access"
    items:
      type: object
      required:
        - name
        - label
        - url
      properties:
        name:
          type: string
          description: "Bookmark app name"
        label:
          type: string
          description: "Bookmark app display label"
        url:
          type: string
          format: uri
          description: "Bookmark app URL"
        status:
          type: string
          enum: ["ACTIVE", "INACTIVE"]
          description: "Bookmark app status"
          default: "ACTIVE"
        auto_submit_toolbar:
          type: boolean
          description: "Auto submit toolbar"
          default: false
        hide_ios:
          type: boolean
          description: "Hide from iOS"
          default: false
        hide_web:
          type: boolean
          description: "Hide from web"
          default: false

# Validation Rules:
# 1. Folder structure must be: apps/DIVISION/APPNAME/ENVIRONMENT/app-config.yaml
# 2. Division name must be one of DIV1-DIV6
# 3. Environment must be one of: dev, uat, prod
# 4. CMDB app short name must be uppercase alphanumeric only
# 5. Division name in YAML must match folder name
# 6. Environment in YAML must match folder name
# 7. Only one 3-leg app type can be true at a time
# 8. 2-leg and 3-leg can be combined (hybrid)
# 9. SAML must be false (not implemented)
# 10. At least one OAuth type must be true
# 11. All URIs must be valid URLs 