# FINANCE_EXPENSE_TRACKER Application Configuration
# This app has both frontend (SPA) and backend (API) components

app_name: "FINANCE_EXPENSE_TRACKER"
app_label: "Finance Expense Tracker"
point_of_contact_email: "finance-team@company.com"
app_owner: "Finance IT Team"
onboarding_snow_request: "SNOWREQ123456"

oauth_config:
  # 2-leg API for backend services
  create_2leg: true
  
  # 3-leg frontend SPA for user interface
  create_3leg_frontend: true
  
  # 3-leg backend web app (not needed for this app)
  create_3leg_backend: false
  
  # 3-leg native app (not needed for this app)
  create_3leg_native: false
  
  # SAML app (not implemented yet)
  create_saml: false
  
  # OAuth scopes
  scopes:
    - "openid"
    - "profile"
    - "email"
    - "finance:read"
    - "finance:write"
    - "finance:admin"
  
  # Redirect URIs (single list for the active OAuth app)
  redirect_uris:
    - "https://finance-expense.company.com/callback"
    - "https://finance-expense.company.com/silent-renew"
    - "https://finance-api.company.com/callback"
    - "http://localhost:3000/callback"  # Development
    - "com.company.finance://callback"
  
  # Post-logout URIs (single list for the active OAuth app)
  post_logout_uris:
    - "https://finance-expense.company.com/logout"
    - "https://finance-expense.company.com/signout"
    - "https://finance-api.company.com/logout"
    - "com.company.finance://logout"

# Trusted Origins configuration
trusted_origins:
  - name: "Finance Expense Tracker Frontend"
    url: "https://finance-expense.company.com"
    scopes: ["CORS", "REDIRECT"]
    status: "ACTIVE"
  
  - name: "Finance Expense Tracker API"
    url: "https://finance-api.company.com"
    scopes: ["CORS", "REDIRECT"]
    status: "ACTIVE"
  
  - name: "Finance Expense Tracker Development"
    url: "http://localhost:3000"
    scopes: ["CORS", "REDIRECT"]
    status: "ACTIVE"

# Bookmarks configuration
bookmarks:
  - name: "Finance Expense Tracker Admin"
    label: "Finance Expense Tracker - Admin Portal"
    url: "https://finance-expense.company.com/admin"
    status: "ACTIVE"
    auto_submit_toolbar: false
    hide_ios: false
    hide_web: false
  
  - name: "Finance Expense Tracker Reports"
    label: "Finance Expense Tracker - Reports"
    url: "https://finance-expense.company.com/reports"
    status: "ACTIVE"
    auto_submit_toolbar: false
    hide_ios: false
    hide_web: false 