app_name = "example-spa"
app_label = "Example SPA App"
grant_types = ["authorization_code", "refresh_token"]
redirect_uris = [
response_types = ["code"]
token_endpoint_auth_method = "none"
pkce_required = true
auto_submit_toolbar = false
hide_ios = false
hide_web = false
issuer_mode = "ORG_URL"
