# HR_EMPLOYEE_PORTAL Application Configuration
# This app is a simple SPA for employee self-service

app_name: "HR_EMPLOYEE_PORTAL"
app_label: "HR Employee Portal"
point_of_contact_email: "hr-ops@company.com"
app_owner: "HR Operations"
onboarding_snow_request: "SNOWREQ654321"

oauth_config:
  # No 2-leg API needed
  create_2leg: false
  
  # 3-leg frontend SPA for employee portal
  create_3leg_frontend: true
  
  # No backend web app needed
  create_3leg_backend: false
  
  # No native app needed
  create_3leg_native: false
  
  # SAML app (not implemented yet)
  create_saml: false
  
  # OAuth scopes
  scopes:
    - "openid"
    - "profile"
    - "email"
    - "hr:read" 