# FINANCE_EXPENSE_TRACKER Application Configuration
# This app has both frontend (SPA) and backend (API) components
# Environment: UAT

cmdb_app_name: "Finance Expense Tracker"
division_name: "DIV1"
cmdb_short_name: "ET"
environment: "uat"
point_of_contact_email: "finance-team@company.com"
app_owner: "Finance IT Team"
onboarding_snow_request: "SNOWREQ123456"

# App Configuration - what to create
app_config:
  create_2leg: true
  create_3leg_frontend: true
  create_3leg_backend: false
  create_3leg_native: false
  create_saml: false

# OAuth Configuration - OAuth app settings
oauth_config:
  # OAuth App Settings
  scopes:
    - "openid"
    - "profile"
    - "email"
    - "finance:read"
    - "finance:write"
    - "finance:admin"
  
  redirect_uris:
    - "https://finance-expense-uat.company.com/callback"
    - "https://finance-expense-uat.company.com/silent-renew"
    - "https://finance-api-uat.company.com/callback"
    - "com.company.finance.uat://callback"
  
  post_logout_uris:
    - "https://finance-expense-uat.company.com/logout"
    - "https://finance-expense-uat.company.com/signout"
    - "https://finance-api-uat.company.com/logout"
    - "com.company.finance.uat://logout"

# Trusted Origins configuration
trusted_origins:
  - name: "Finance Expense Tracker Frontend UAT"
    url: "https://finance-expense-uat.company.com"
    scopes: ["CORS", "REDIRECT"]
    status: "ACTIVE"
  
  - name: "Finance Expense Tracker API UAT"
    url: "https://finance-api-uat.company.com"
    scopes: ["CORS", "REDIRECT"]
    status: "ACTIVE"

# Bookmarks configuration
bookmarks:
  - name: "Finance Expense Tracker Admin UAT"
    label: "Finance Expense Tracker - Admin Portal (UAT)"
    url: "https://finance-expense-uat.company.com/admin"
    status: "ACTIVE"
    auto_submit_toolbar: false
    hide_ios: false
    hide_web: false
  
  - name: "Finance Expense Tracker Reports UAT"
    label: "Finance Expense Tracker - Reports (UAT)"
    url: "https://finance-expense-uat.company.com/reports"
    status: "ACTIVE"
    auto_submit_toolbar: false
    hide_ios: false
    hide_web: false 